### ISSUE TITLE
Improve Cloud Run responsiveness

### ISSUE THREAD

**Issue by mshidlov** [amplication/blog-server#19]
Change the cloud run deployment to be more responsive.
set the production cloud run:

1. CPU to 4
2. memory to 4g
3. min instances to 1
4. min instances to 5
5. set the concurrency to 100
6. set allocate always-on CPU
7. change database to be `db-custom-2-4096`

**Comment by shaharblanksela** [comment]
The database_tier should be "db-custom-4-4096" if the CPU is 4.
